---
name: Automerge PR

on: pull_request

jobs:
  automerge:
    name: Automerge PR
    runs-on: ubuntu-latest
    environment:
      name: "pr"
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Enable pull request automerge
        run: gh pr merge --merge --auto "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
